name: Build CI

on:
  workflow_dispatch:
  push:
    branches: [main, gcc-build]
  pull_request:
    types: [opened, synchronize]
    branches: [main]

env:
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"

jobs:
  build-native-linux:
    name: Build native Linux libraries
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'        
      - name: Cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build native libraries with gradle
        run: ./gradlew makeNative64
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            native-gcc/bin/Release/Linux/32/*.so
            native-gcc/bin/Release/Linux/64/*.so
          name: LinuxNativeLibs
  build-native-windows:
    name: Build native Windows libraries
    runs-on: windows-latest
    needs: build-native-linux
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'        
      - name: Cache gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-caches-${{ hashFiles('**/*.gradle') }}
          restore-keys: |
            ${{ runner.os }}-gradle-caches-
      - name: Cache gradle wrapper
        uses: actions/cache@v2
        with:
          path: ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-wrapper-${{ hashFiles('**/gradle/wrapper/gradle-wrapper.properties') }}
      - name: Download Linux native artifacts
        uses: actions/download-artifact@v2
        with:
          name: LinuxNativeLibs
          path: native-gcc/bin/Release/Linux/
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Build native libraries with gradle
        run: ./gradlew makeNative64 makeNativeWrappers
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            native-gcc/bin/Release/Linux/32/*.so
            native-gcc/bin/Release/Linux/64/*.so
            native-gcc/bin/Release/Windows/32/*.dll
            native-gcc/bin/Release/Windows/64/*.dll
            csharp/EPAM.Deltix.DFP/NativeImpl.cs
            csharp/EPAM.Deltix.DFP/Version.targets
            java/src/main/java/com/epam/deltix/dfp/NativeImpl.java
            java/src/main/java/com/epam/deltix/dfp/Version.java
          name: NativeLibs
  compress:
    name: Compress native libraries
    runs-on: ubuntu-latest
    needs: build-native-windows
    steps:
      - name: Checkout code
        uses: actions/checkout@v2      
      - name: Download artifacts
        uses: actions/download-artifact@v2
        with:
          name: NativeLibs
      - name: Install zstd
        run: sudo apt-get install -y zstd
      - name: Compress native libraries with zstd
        run: zstd -19 --rm -r ./native-gcc/bin
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          path: |
            native-gcc/bin
            csharp/EPAM.Deltix.DFP/NativeImpl.cs
            csharp/EPAM.Deltix.DFP/Version.targets
            java/src/main/java/com/epam/deltix/dfp/NativeImpl.java
            java/src/main/java/com/epam/deltix/dfp/Version.java
          name: CompressedNativeLibs
    